### PR TITLE
Remove peer dependency

### PR DESCRIPTION
**Pull request by IrisArvato**

### CODE REVIEW

**Comment by IrisArvato** [comment]
@madsthom can you help my PR again for remove peer dependency

**Comment by madsthom** [comment]
@IrisArvato It is now merged and published to npm registry. Can you confirm that it works for the new published package? - Thanks again for contributing. I might add you on npm registry so you can publish yourself. Would you be interested in that? 😄

**Comment by IrisArvato** [comment]
Hi @madsthom , the package does not work. I believe you should not publish directly from the root folder, but should publish the npm from the dist folder after run **yarn build:lib**

**Comment by madsthom** [comment]
Ah, yes ofc. A long til since I updated. My bad. Will revert ASAP.

**Comment by madsthom** [comment]
@IrisArvato It should be update now. Sorry for the mistake. I haven't develop any Angular packages in a long time. Is it fixed now?

**Comment by madsthom** [comment]
@IrisArvato: If you want to be a maintainer on npm registry, then please supply your username, then I can invite you.

**Comment by IrisArvato** [comment]
> @IrisArvato: If you want to be a maintainer on npm registry, then please supply your username, then I can invite you.

ok, please invite me. Thank you :)
Here is my npm username: yisynn

**Pull request merged**
