### PR TITLE
Upgrade to angular 15

### PR DESCRIPTION
**Pull request by IrisArvato**

### CODE REVIEW

**Comment by IrisArvato** [comment]
Hi @madsthom , can you help to review my PR on upgrading this to angular 15?

**Comment by madsthom** [comment]
Thanks for your contribution. I will review today. 👍🏼 Make sure all unit tests pass, then I think it is ready to merge and release.

**Comment by IrisArvato** [comment]
@madsthom  I do the fix on the unit test yesterday and the all test should passed now. can you help to do the merge and release?

**Comment by madsthom** [comment]
@IrisArvato I have some trouble getting the unit tests to run on the new versionen. Maybe it's my local setup. Maybe we should just merge and update and then you can try it out in out own project? - if I release, can you try it out on a local project?

**Comment by IrisArvato** [comment]
@madsthom that will be good. I already test that by building the package manually and referencing it in my local project, and it working fine.

**Comment by madsthom** [comment]
@IrisArvato I have some trouble building the package with `yarn build:prod`. Can you try and do it on your end?

**Comment by IrisArvato** [comment]
@madsthom yarn build:prod running fine in my end. May I know what is the error you get?

**Pull request merged**
