### PR TITLE
Angular 18 upgrade

### PR DESCRIPTION
**Pull request by AndreyChayko**
- Performed the full update to Angular 18.2.0
- Removed redundant files, configs, links, settings

### CODE REVIEW

**Comment by AndreyChayko** [comment]
Didn't do anything with e2e cause it seems nothing is used and was created automatically a long time ago.

The rest of stuff still works as expected, unit tests are passed 

@madsthom Can you please review and merge if it is okay?

**Comment by AndreyChayko** [comment]
@yp2 or may be you can do it instead :D

**Comment by madsthom** [comment]
@AndreyChayko Thanks for the contribution. I will try and make an npm release (sucessfully this time ;-) )

**Comment by madsthom** [comment]
@AndreyChayko if I add you as maintainer on npmjs would you be able to create the release?

**Comment by madsthom** [comment]
@AndreyChayko: Did a release. Can you verify that it works?

**Comment by AndreyChayko** [comment]
@madsthom  thanks man, will check it soon, sorry for the late response

Regarding the role of maintainer, we can have a try, I will try to watch the repo

**Comment by AndreyChayko** [comment]
@madsthom works fine for our project !

**Comment by madsthom** [comment]
@AndreyChayko Great!!

**Pull request merged**
