### PR TITLE
Upgraded dev/peer dep. to angular 11

### PR DESCRIPTION
**Pull request by madsthom**
Hi Daniel (@yp2)

Thanks for this awesome library.

I it possible to upgrade the project to Angular 11?

This is a PR for updating some packages (peer and dev dependencies) to Angular 11. I can so it for Angular 10 (LTS) instead. I have not yet edited the README to fit Angular 11.

If this it no longer maintained, do you recommend forking it and release a version myself?

### CODE REVIEW

**Comment by amelnikoff** [comment]
Looks like library is dead.

**Comment by yp2** [comment]
Hi, I'm sorry I have a lite time to spend on this project. Today I will try to build package for version 11.0.3

**Comment by yp2** [comment]
@madsthom If you want, I can add you as a maintainer to npm.

**Comment by yp2** [comment]
@madsthom package uploaded to npm.

**Comment by madsthom** [comment]
> @madsthom If you want, I can add you as a maintainer to npm.

Yes, sure. That would be cool. Thanks for your response @yp2. Happy Holidays! 🎄

**Comment by yp2** [comment]
@madsthom can you provide your npm login?

**Comment by madsthom** [comment]
@yp2 Its the same as my github: madsthom

**Comment by yp2** [comment]
@madsthom done.

**Pull request merged**
